FROM alpine:3.14
ENV INPUT_LOCATION=/input
ENV OUTPUT_LOCATION=/output
COPY hello-go-gradle /
ENTRYPOINT ["/hello-go-gradle"]

# see: https://github.com/GoogleContainerTools/distroless/blob/main/examples/go/Dockerfile
