FROM alpine:3.14
ENV INPUT_LOCATION=/input
ENV OUTPUT_LOCATION=/output
COPY hello-mage /
ENTRYPOINT ["/hello-mage"]

# see: https://github.com/GoogleContainerTools/distroless/blob/main/examples/go/Dockerfile
